---

- name: add primary group {{ oracle_user.primary_group }}
  group:
    name: "{{ oracle_user.primary_group }}"
    state: present
    gid: "{{ oracle_user.primary_group_gid }}"
  register: add_primary_group

- name: verify add primary group {{ oracle_user.primary_group}}
  debug: var=add_primary_group

- name: add secondary group {{ oracle_user.secondary_group }}
  group:
    name: "{{ oracle_user.secondary_group }}"
    state: present
    gid: "{{ oracle_user.secondary_group_gid }}"
  register: add_secondary_group

- name: verify add secondary group {{ oracle_user.secondary_group }}
  debug: var=add_secondary_group

- name: add user oracle user {{ oracle_user.name }}
  user:
    name: "{{ oracle_user.name }}"
    uid: "{{ oracle_user.uid }}"
    group: "{{ oracle_user.primary_group }}"
    groups: "{{ oracle_user.secondary_group }}"
    shell: /bin/bash
    expires: -1
  register: add_oracle_user

- name: verify add user {{ oracle_user.name }}
  debug: var=add_oracle_user

- name: set kernal parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items: "{{ kernel_parameters }}" 
  register: set_kernel_parameters

- name: verify set kernal parameters
  debug: var=set_kernel_parameters

- name: set {{ oracle_user.name }} user limits
  pam_limits:
    domain: "{{ oracle_user.name }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items: "{{ user_limits }}"
  register: set_user_limits

- name: verify set user limits
  debug: var=set_user_limits



