---

- name: add primary group {{ primary_group }}
  group:
    name: "{{ primary_group }}"
    state: present
    gid: 101
  register: add_primary_group

- name: verify add primary group {{ primary_group}}
  debug: var=add_primary_group

- name: add secondary group {{ secondary_group }}
  group:
    name: "{{ secondary_group }}"
    state: present 
    gid: 102
  register: add_secondary_group

- name: verify add secondary group {{ secondary_group }}
  debug: var=add_secondary_group

- name: add user oracle user {{ oracle_user }}
  user:
    name: "{{ oracle_user }}"
    uid: 100
    group: "{{ primary_group }}"
    groups: "{{ secondary_group }}"
    shell: /bin/bash
    expires: -1
  register: add_oracle_user

- name: verify add user {{ oracle_user }}
  debug: var=add_oracle_user
